### ISSUE TITLE
Make a basic structure of project and create a user module, display "welcome Admin" on UI

### ISSUE THREAD

**Issue by Ashu002** [Ashu002/UserManagement#2]
@rahulsingh1992 Plase design an app in agularJS1 and display a welcome message on view with user module. Use npm as a build tool. 
Let me know if there is any issue you are facing.

**Comment by rahulsingh1992** [comment]
@Ashu002  Mr Ashu  Welcome Massage in Angular js 1 are Display and prepair file structure in angular

**Comment by rahulsingh1992** [comment]
By bower install

**Comment by rahulsingh1992** [comment]
PR has been merged.... Closing the issue.
